# build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

header_pages:
  - roadmap.md
  - docs/c/v2-2-0/en-US/index.html
  - docs/cpp/v2-2-0/en-US/index.html

exclude:
  - script_*
