version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

jobs:
  build:
    docker:
#      - image: 'node:latest'
       - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install Sonarcloud Build Wrapper
          command: |
            wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
            unzip build-wrapper-linux-x86.zip
            cp build-wrapper-linux-x86/libinterceptor-x86_64.so build-wrapper-linux-x86/libinterceptor-haswell.so
      - run:
          name: Build and Test
          command: |
            sudo apt update && sudo apt install -y cmake make gcc
            cmake -DCOVERAGE=ON .
            ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir /tmp make VERBOSE=1
            make check
      - sonarcloud/scan
