version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

workflows:
  main:
    jobs:
      - build:

jobs:
  build:
    docker:
#      - image: 'node:latest'
       - image: cimg/base:2020.01
    steps:
      - checkout
      - sonarcloud/scan
