version: "0.4.0"
classes:
  - name: "Param"
    namespace: "stumplesscpp"
    type: "pointer"
    equivalent-struct:
      name: "stumpless_param"
      includes: "stumpless/entry.h"
    constructors:
      - wrapped-function:
          name: "stumpless_new_param"
          includes: "stumpless/entry.h"
          params:
            - name: "name"
              doc: "The name of the parameter."
              type: "const char *"
            - name: "value"
              doc: "The value of the parameter"
              type: "const char *"
          return:
            type: "equivalent-struct-pointer"
    destructor:
      wrapped-function:
        name: "stumpless_destroy_param"
        includes: "stumpless/entry.h"
        params:
          - name: "equivalent-struct-pointer"
