version: "0.4.0"
classes:
  - name: "Param"
    doc: "A parameter within a structured data element."
    namespace: "stumplesscpp"
    type: "pointer"
    equivalent-struct:
      name: "stumpless_param"
      includes: "stumpless/entry.h"
    constructors:
      - doc: "Creates a new Param with the given name and value."
        wrapped-function:
          name: "stumpless_new_param"
          includes: "stumpless/entry.h"
          params:
            - name: "name"
              doc: "The name of the parameter."
              type: "const char *"
            - name: "value"
              doc: "The value of the parameter"
              type: "const char *"
          return:
            type: "equivalent-struct-pointer"
#          use-template: "pointer-return-error-check"
    destructor:
      doc: "Destroys this parameter and releases all memory allocated for it."
      wrapped-function:
        name: "stumpless_destroy_param"
        includes: "stumpless/entry.h"
        params:
          - name: "equivalent-struct-pointer"
