set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "a fast C logging library")
set(CPACK_PACKAGE_CONTACT "Joel Anderson <joelanderson333@gmail.com>")
set(CPACK_PACKAGE_VENDOR "Goatshriek Software")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

file(COPY "${PROJECT_SOURCE_DIR}/COPYING"
  DESTINATION ${PROJECT_BINARY_DIR})
file(RENAME "${PROJECT_BINARY_DIR}/COPYING" "${PROJECT_BINARY_DIR}/COPYING.txt")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_BINARY_DIR}/COPYING.txt")


# WIX settings
set(CPACK_WIX_PRODUCT_GUID "c0ac11a2-d1ab-4aa9-9f4f-b67d7c6db291")
set(CPACK_WIX_UPGRADE_GUID "21affd82-0719-4144-9f54-5e893a08633d")


include(CPack)
