set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "a fast C logging library")
set(CPACK_PACKAGE_CONTACT "Joel Anderson <joelanderson333@gmail.com>")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})


set(CPACK_RESOURCE_FILE_LICENSE ${PROJECT_SOURCE_DIR}/COPYING)

include(CPack)
