.TH "stumpless/level Directory Reference" 3 "Version 3.0.0" "stumpless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stumpless/level Directory Reference \- Header files for working with specific logging levels\&.  

.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalert\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the alert level\&. "
.ti -1c
.RI "file \fBcrit\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the crit level\&. "
.ti -1c
.RI "file \fBdebug\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the debug level\&. "
.ti -1c
.RI "file \fBemerg\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the emerg level\&. "
.ti -1c
.RI "file \fBerr\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the err level\&. "
.ti -1c
.RI "file \fBinfo\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the info level\&. "
.ti -1c
.RI "file \fBmask\&.h\fP"
.br
.RI "Masks that provide shorthand for enabling or disabling logging levels at compile time\&. "
.ti -1c
.RI "file \fBnotice\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the notice level\&. "
.ti -1c
.RI "file \fBtrace\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the trace level\&. "
.ti -1c
.RI "file \fBwarning\&.h\fP"
.br
.RI "Macro functions that log messages and entries at the warning level\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header files for working with specific logging levels\&. 
