.TH "stumpless Directory Reference" 3 "Version 3.0.0" "stumpless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stumpless Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBconfig\fP"
.br
.RI "Configuration-specific header files\&. "
.ti -1c
.RI "directory \fBlevel\fP"
.br
.RI "Header files for working with specific logging levels\&. "
.ti -1c
.RI "directory \fBtarget\fP"
.br
.RI "Header files for target types provided by the library\&. "
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.RI "Configuration information to provide to code built with the library\&. "
.ti -1c
.RI "file \fBelement\&.h\fP"
.br
.RI "Types and functions for creating and modifying elements\&. "
.ti -1c
.RI "file \fBentry\&.h\fP"
.br
.RI "Types and functions for creating and modifying entries\&. "
.ti -1c
.RI "file \fBerror\&.h\fP"
.br
.RI "Error codes and functions for detecting and assessing them\&. "
.ti -1c
.RI "file \fBfacility\&.h\fP"
.br
.RI "Facility codes for classifying log entries\&. "
.ti -1c
.RI "file \fBfilter\&.h\fP"
.br
.RI "Filters that can be used to control which entries are sent to targets at runtime\&. "
.ti -1c
.RI "file \fBgenerator\&.h\fP"
.br
.RI "Generic functionality to be used with STUMPLESS_FOREACH macros to allow for more generic definition of enumerations and to string functions\&. "
.ti -1c
.RI "file \fBid\&.h\fP"
.br
.RI "The identification for targets within the library\&. "
.ti -1c
.RI "file \fBlog\&.h\fP"
.br
.RI "Convenience functions for creating and writing simple log entries\&. "
.ti -1c
.RI "file \fBmemory\&.h\fP"
.br
.RI "Functions for controlling memory allocation during execution\&. "
.ti -1c
.RI "file \fBoption\&.h\fP"
.br
.RI "Options that can be used to modify the behavior of Stumpless components\&. "
.ti -1c
.RI "file \fBparam\&.h\fP"
.br
.RI "Types and functions for creating and modifying params\&. "
.ti -1c
.RI "file \fBprival\&.h\fP"
.br
.RI "Functions for working with privals, which contain both facility and severity values\&. "
.ti -1c
.RI "file \fBseverity\&.h\fP"
.br
.RI "Severity codes for classifying log entries\&. "
.ti -1c
.RI "file \fBtarget\&.h\fP"
.br
.RI "General types and functions for working with all targets\&. "
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.RI "Runtime information about the library\&. "
.in -1c
