.TH "stumpless/config Directory Reference" 3 "Version 3.0.0" "stumpless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stumpless/config Directory Reference \- Configuration-specific header files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjournald_supported\&.h\fP"
.br
.RI "Functions that help when using journald targets\&. "
.ti -1c
.RI "file \fBwel_supported\&.h\fP"
.br
.RI "Functions necessary when using Windows Event Log targets\&. "
.in -1c
.SH "Detailed Description"
.PP 
Configuration-specific header files\&. 
