.TH "stumpless/id.h" 3 "Version 3.0.0" "stumpless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stumpless/id.h \- The identification for targets within the library\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBstumpless_id_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The identification for targets within the library\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBstumpless_id_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for stumpless from the source code\&.
