.TH "stumpless/prival.h" 3 "Version 3.0.0" "stumpless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stumpless/prival.h \- Functions for working with privals, which contain both facility and severity values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBstumpless_get_prival_string\fP (int prival)"
.br
.RI "Gets the string representation of the given prival\&. "
.ti -1c
.RI "const char * \fBstumpless_get_priority_string\fP (int prival)"
.br
.RI "Gets the string representation of the given prival in the format 'facility\&.level'\&. "
.ti -1c
.RI "int \fBstumpless_prival_from_string\fP (const char *string)"
.br
.RI "Extract PRIVAL number (Facility and Severity) from the given string with the direct number or with two names divided with a period in the order: facility first, then severity ('<facility_descr>\&.<severity_descr>')\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functions for working with privals, which contain both facility and severity values\&. 


.PP
\fBSince\fP
.RS 4
release v2\&.2\&.0 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "const char * stumpless_get_priority_string (int prival)"

.PP
Gets the string representation of the given prival in the format 'facility\&.level'\&. The string returned must be freed by the caller when it is no longer needed to avoid memory leaks\&.
.PP
\fBThread Safety: MT-Safe\fP This function is thread safe\&.
.PP
\fBAsync Signal Safety: AS-Unsafe heap\fP This function is not safe to call from signal handlers due to the use of memory management functions\&.
.PP
\fBAsync Cancel Safety: AC-Unsafe heap\fP This function is not safe to call from threads that may be asynchronously cancelled due to the use of memory management functions\&.
.PP
\fBParameters\fP
.RS 4
\fIprival\fP int to get the string from\&.
.RE
.PP
\fBReturns\fP
.RS 4
The string representation of the given prival\&. 
.RE
.PP

.SS "const char * stumpless_get_prival_string (int prival)"

.PP
Gets the string representation of the given prival\&. The string returned must be freed by the caller when it is no longer needed to avoid memory leaks\&.
.PP
\fBThread Safety: MT-Safe\fP This function is thread safe\&.
.PP
\fBAsync Signal Safety: AS-Unsafe heap\fP This function is not safe to call from signal handlers due to the use of memory management functions\&.
.PP
\fBAsync Cancel Safety: AC-Unsafe heap\fP This function is not safe to call from threads that may be asynchronously cancelled due to the use of memory management functions\&.
.PP
\fBSince\fP
.RS 4
release v2\&.2\&.0
.RE
.PP
\fBParameters\fP
.RS 4
\fIprival\fP int to get the string from\&.
.RE
.PP
\fBReturns\fP
.RS 4
The string representation of the given prival\&. 
.RE
.PP

.SS "int stumpless_prival_from_string (const char * string)"

.PP
Extract PRIVAL number (Facility and Severity) from the given string with the direct number or with two names divided with a period in the order: facility first, then severity ('<facility_descr>\&.<severity_descr>')\&. In release v2\&.2\&.0 this function was in a separate header 'stumpless/priority\&.h'\&. This header was consolidated into 'stumpless/prival\&.h' in release v3\&.0\&.0\&.
.PP
\fBThread Safety: MT-Safe\fP This function is thread safe\&. A mutex is used to coordinate changes to the target while it is being read\&.
.PP
\fBAsync Signal Safety: AS-Unsafe lock\fP This function is not safe to call from signal handlers due to the use of a non-reentrant lock to coordinate the read of the target\&.
.PP
\fBAsync Cancel Safety: AC-Unsafe lock\fP This function is not safe to call from threads that may be asynchronously cancelled, due to the use of a lock that could be left locked\&.\&.
.PP
\fBSince\fP
.RS 4
release v2\&.2\&.0
.RE
.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to extract the prival from\&.
.RE
.PP
\fBReturns\fP
.RS 4
the PRIVAL number used for the severity and facility values of the logged entry, in the event of an error it returns -1\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for stumpless from the source code\&.
