.TH "stumpless_version" 3 "Version 3.0.0" "stumpless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stumpless_version \- A description of a library version\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <version\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmajor\fP"
.br
.RI "The major version\&. "
.ti -1c
.RI "int \fBminor\fP"
.br
.RI "The minor version\&. "
.ti -1c
.RI "int \fBpatch\fP"
.br
.RI "The patch version\&. "
.in -1c
.SH "Detailed Description"
.PP 
A description of a library version\&. 

This project follows semantic versioning\&. 
.SH "Field Documentation"
.PP 
.SS "int stumpless_version::major"

.PP
The major version\&. 
.SS "int stumpless_version::minor"

.PP
The minor version\&. 
.SS "int stumpless_version::patch"

.PP
The patch version\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stumpless from the source code\&.
