.TH "stumpless.h" 3 "Version 3.0.0" "stumpless" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stumpless.h \- The main header file for the stumpless logging library\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The main header file for the stumpless logging library\&. 

Unless you are specifically trying to include ONLY required headers, it is best to simply include this header to use stumpless\&. It will ensure that all available features are declared, as well as take care of any ordering or conditional includes that may be necessary on the target platform\&.
.PP
If you do want to only include specific header files, you can use this file as a template\&. Note that all headers are under the stumpless directory, which must be in the include path\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for stumpless from the source code\&.
