#ifndef __STUMPLESS_TYPE_DECLARATION_H
#define __STUMPLESS_TYPE_DECLARATION_H

struct Adapter;
struct AdapterList;
struct AdapterListConstIterator;
struct AdapterListConstReverseIterator;
struct AdapterListIterator;
struct AdapterListReverseIterator;
struct Boolean;
struct BooleanFormat;
struct ByteList;
struct Comparator;
struct ComparatorList;
struct ComparatorListConstIterator;
struct ComparatorListConstReverseIterator;
struct ComparatorListIterator;
struct ComparatorListReverseIterator;
struct Configuration;
struct Dictionary;
struct Entry;
struct EntryAttribute;
struct EntryAttributeList;
struct EntryAttributeListConstIterator;
struct EntryAttributeListConstReverseIterator;
struct EntryAttributeListIterator;
struct EntryAttributeListReverseIterator;
struct Event;
struct EventAttribute;
struct EventAttributeList;
struct EventAttributeListConstIterator;
struct EventAttributeListConstReverseIterator;
struct EventAttributeListIterator;
struct EventAttributeListReverseIterator;
struct FileConfiguration;
struct Filter;
struct FilterList;
struct FilterListConstIterator;
struct FilterListConstReverseIterator;
struct FilterListIterator;
struct FilterListReverseIterator;
struct Formatter;
struct FormatterList;
struct FormatterListConstIterator;
struct FormatterListConstReverseIterator;
struct FormatterListIterator;
struct FormatterListReverseIterator;
struct Handler;
struct HandlerList;
struct HandlerListConstIterator;
struct HandlerListConstReverseIterator;
struct HandlerListIterator;
struct HandlerListReverseIterator;
struct HTTConfiguration;
enum HTTPMethod;
struct Level;
struct Log;
struct Logger;
struct Output;
struct OutputProfile;
struct Record;
struct RecordList;
struct Status;
struct SortingConfiguration;
enum SortingMethod;
struct StringConfiguration;
struct Target;
struct TargetList;
struct ThreadingConfiguration;
union Type;
struct Value;
struct ValueList;
struct ValueListConstIterator;
struct ValueListConstReverseIterator;
struct ValueListIterator;
struct ValueListReverseIterator;
struct ValueProfile;

typedef struct Adapter Adapter;
typedef struct AdapterList AdapterList;
typedef struct AdapterListConstIterator AdapterListConstIterator;
typedef struct AdapterListConstReverseIterator AdapterListConstReverseIterator;
typedef struct AdapterListIterator AdapterListIterator;
typedef struct AdapterListReverseIterator AdapterListReverseIterator;
typedef struct Boolean Boolean;
typedef struct BooleanFormat BooleanFormat;
typedef struct ByteList ByteList;
typedef struct Comparator Comparator;
typedef struct ComparatorList ComparatorList;
typedef struct ComparatorListConstIterator ComparatorListConstIterator;
typedef struct ComparatorListConstReverseIterator ComparatorListConstReverseIterator;
typedef struct ComparatorListIterator ComparatorListIterator;
typedef struct ComparatorListReverseIterator ComparatorListReverseIterator;
typedef struct Configuration Configuration;
typedef struct Dictionary Dictionary;
typedef struct Entry Entry;
typedef struct EntryAttribute EntryAttribute;
typedef struct EntryAttributeList EntryAttributeList;
typedef struct EntryAttributeListConstIterator EntryAttributeListConstIterator;
typedef struct EntryAttributeListConstReverseIterator EntryAttributeListConstReverseIterator;
typedef struct EntryAttributeListIterator EntryAttributeListIterator;
typedef struct EntryAttributeListReverseIterator EntryAttributeListReverseIterator;
typedef struct Event Event;
typedef struct EventAttribute EventAttribute;
typedef struct EventAttributeList EventAttributeList;
typedef struct EventAttributeListConstIterator EventAttributeListConstIterator;
typedef struct EventAttributeListConstReverseIterator EventAttributeListConstReverseIterator;
typedef struct EventAttributeListIterator EventAttributeListIterator;
typedef struct EventAttributeListReverseIterator EventAttributeListReverseIterator;
typedef struct FileConfiguration FileConfiguration;
typedef struct Filter Filter;
typedef struct FilterList FilterList;
typedef struct FilterListConstIterator FilterListConstIterator;
typedef struct FilterListConstReverseIterator FilterListConstReverseIterator;
typedef struct FilterListIterator FilterListIterator;
typedef struct FilterListReverseIterator FilterListReverseIterator;
typedef struct Formatter Formatter;
typedef struct FormatterList FormatterList;
typedef struct FormatterListConstIterator FormatterListConstIterator;
typedef struct FormatterListConstReverseIterator FormatterListConstReverseIterator;
typedef struct FormatterListIterator FormatterListIterator;
typedef struct FormatterListReverseIterator FormatterListReverseIterator;
typedef struct Handler Handler;
typedef struct HandlerList HandlerList;
typedef struct HandlerListConstIterator HandlerListConstIterator;
typedef struct HandlerListConstReverseIterator HandlerListConstReverseIterator;
typedef struct HandlerListIterator HandlerListIterator;
typedef struct HandlerListReverseIterator HandlerListReverseIterator;
typedef struct HTTPConfiguration HTTPConfiguration;
typedef enum HTTPMethod HTTPMethod;
typedef struct Level Level;
typedef struct Log Log;
typedef struct Logger Logger;
typedef struct Output Output;
typedef struct OutputProfile OutputProfile;
typedef struct Record Record;
typedef struct RecordList RecordList;
typedef struct Status Status;
typedef struct SortingConfiguration SortingConfiguration;
typedef enum SortingMethod SortingMethod;
typedef struct StringConfiguration StringConfiguration;
typedef struct Target Target;
typedef struct TargetList TargetList;
typedef struct ThreadingConfiguration ThreadingConfiguration;
typedef union Type Type;
typedef struct Value Value;
typedef struct ValueList ValueList;
typedef struct ValueListConstIterator ValueListConstIterator;
typedef struct ValueListConstReverseIterator ValueListConstReverseIterator;
typedef struct ValueListIterator ValueListIterator;
typedef struct ValueListReverseIterator ValueListReverseIterator;
typedef struct ValueProfile ValueProfile;

typedef unsigned char Byte;

#endif
