#ifndef __STUMPLESS_TYPE_DECLARATION_H
#define __STUMPLESS_TYPE_DECLARATION_H

struct Adapter;
struct AdapterList;
struct AdapterListIterator;
struct Boolean;
struct BooleanFormat;
struct ByteList;
struct Comparator;
struct ComparatorList;
struct ComparatorListIterator;
struct Configuration;
struct Dictionary;
struct Entry;
struct EntryAttribute;
struct EntryAttributeList;
struct EntryAttributeListIterator;
struct Event;
struct EventAttribute;
struct EventAttributeList;
struct EventAttributeListIterator;
struct FileConfiguration;
struct Filter;
struct FilterList;
struct FilterListIterator;
struct Formatter;
struct FormatterList;
struct FormatterListIterator;
struct Handler;
struct HandlerList;
struct HandlerListIterator;
struct HTTConfiguration;
enum HTTPMethod;
struct Level;
struct Log;
struct Logger;
struct Output;
struct OutputProfile;
struct Record;
struct RecordList;
struct Status;
struct SortingConfiguration;
enum SortingMethod;
struct StringConfiguration;
struct ThreadingConfiguration;
union Type;
struct Value;
struct ValueList;
struct ValueListIterator;
struct ValueProfile;

typedef struct Adapter Adapter;
typedef struct AdapterList AdapterList;
typedef struct AdapterListIterator AdapterListIterator;
typedef struct Boolean Boolean;
typedef struct BooleanFormat BooleanFormat;
typedef struct ByteList ByteList;
typedef struct Comparator Comparator;
typedef struct ComparatorList ComparatorList;
typedef struct ComparatorListIterator ComparatorListIterator;
typedef struct Configuration Configuration;
typedef struct Dictionary Dictionary;
typedef struct Entry Entry;
typedef struct EntryAttribute EntryAttribute;
typedef struct EntryAttributeList EntryAttributeList;
typedef struct EntryAttributeListIterator EntryAttributeListIterator;
typedef struct Event Event;
typedef struct EventAttribute EventAttribute;
typedef struct EventAttributeList EventAttributeList;
typedef struct EventAttributeListIterator EventAttributeListIterator;
typedef struct FileConfiguration FileConfiguration;
typedef struct Filter Filter;
typedef struct FilterList FilterList;
typedef struct FilterListIterator FilterListIterator;
typedef struct Formatter Formatter;
typedef struct FormatterList FormatterList;
typedef struct FormatterListIterator FormatterListIterator;
typedef struct Handler Handler;
typedef struct HandlerList HandlerList;
typedef struct HandlerListIterator HandlerListIterator;
typedef struct HTTPConfiguration HTTPConfiguration;
typedef enum HTTPMethod HTTPMethod;
typedef struct Level Level;
typedef struct Log Log;
typedef struct Logger Logger;
typedef struct Output Output;
typedef struct OutputProfile OutputProfile;
typedef struct Record Record;
typedef struct RecordList RecordList;
typedef struct Status Status;
typedef struct SortingConfiguration SortingConfiguration;
typedef enum SortingMethod SortingMethod;
typedef struct StringConfiguration StringConfiguration;
typedef struct ThreadingConfiguration ThreadingConfiguration;
typedef union Type Type;
typedef struct Value Value;
typedef struct ValueList ValueList;
typedef struct ValueListIterator ValueListIterator;
typedef struct ValueProfile ValueProfile;

typedef unsigned char Byte;

#endif
