name: "build"
on:
  push:
  pull_request:
    branches:
      - latest
jobs:
  basic-linux:
    name: "basic linux build"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cmake -DCOVERAGE=ON .
          make all
          make check
          make examples
      - name: Codecov Upload
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
  basic-mac:
    name: "basic mac os build"
    runs-on: "macos-11.0"
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cmake -DCOVERAGE=ON .
          make all
          make check
          make examples
      - name: Codecov Upload
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
