name: "ci"
on:
  push:
  pull_request:
    branches:
      - latest
jobs:
  basic-linux:
    name: "basic linux build"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake .
          make all
          make check
          make examples
  basic-mac:
    name: "basic mac os build"
    runs-on: "macos-11.0"
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake .
          make all
          make check
          make examples
